import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {compareCriteria,generateMappings,similarity} from '../src/mapping.js';import {flattenCourse} from '../src/course.js';
const course=JSON.parse(await readFile('level3-trowel-6570-05-FULL-course-data.json'));const rows=flattenCourse(course),mappings=generateMappings(course);const ac=(u,id)=>rows.find(x=>x.unit.id===u&&x.ac.id===id).ac;
test('equivalent practical text is automatic despite grammar and context',()=>{const a={wording:'Interpret drawings, specifications and method statements for masonry structures',operativeVerb:'interpret',evidenceClass:'practical'},b={wording:'interpret drawing specification and method statement for masonry cladding',operativeVerb:'interpret',evidenceClass:'practical'};assert.equal(compareCriteria(a,b).mappingType,'automatic')});
test('confirmation and hidden thresholds are applied',()=>{const a={wording:'select maintain tools equipment material safely',operativeVerb:'select',evidenceClass:'practical'},b={wording:'select tools equipment for installation quality',operativeVerb:'select',evidenceClass:'practical'};const m=compareCriteria(a,b);assert.ok(m&&m.similarity>=.4&&m.similarity<.7);assert.equal(m.mappingType,'confirm');assert.equal(compareCriteria(a,{wording:'explain weather delays',operativeVerb:'explain',evidenceClass:'practical'}),null)});
test('cross-class matches are prohibited in either direction',()=>{const p={wording:'use protective equipment safely',operativeVerb:'use',evidenceClass:'practical'},k={...p,evidenceClass:'knowledge'};assert.equal(compareCriteria(p,k),null);assert.equal(compareCriteria(k,p),null)});
test('generic boilerplate cannot make false automatic match',()=>assert.ok(similarity('in accordance with workplace requirements for the activity','in accordance with workplace requirements for the activity')<.7));
test('actual 235.1.1 maps strongly and automatically to 234.1.1',()=>{const m=mappings.find(x=>x.sourceUnit==='235'&&x.sourceAC==='1.1'&&x.targetUnit==='234'&&x.targetAC==='1.1');assert.ok(m);assert.equal(m.evidenceClass,'practical');assert.equal(m.mappingType,'automatic');assert.ok(m.similarity>=.7)});
test('every generated mapping resolves and preserves class',()=>{for(const m of mappings){const s=ac(m.sourceUnit,m.sourceAC),t=ac(m.targetUnit,m.targetAC);assert.equal(s.evidenceClass,t.evidenceClass);assert.equal(m.evidenceClass,s.evidenceClass);assert.ok(m.similarity>=.4)}});
test('mapping inventory is reproducible',()=>{const automatic=mappings.filter(x=>x.mappingType==='automatic').length,confirm=mappings.filter(x=>x.mappingType==='confirm').length;assert.ok(automatic>0);assert.ok(confirm>0);console.log(`mapping inventory: ${automatic} automatic, ${confirm} confirmation-required`)});
