import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {normaliseAssessment,nextEvidenceReference,applySignatureSnapshot,invalidateSignature,materialAssessmentChanged} from '../src/evidence.js';import {assessmentPdfText} from '../src/pdf.js';import {deriveMatrix} from '../src/matrix.js';
const read=p=>readFile(new URL('../'+p,import.meta.url),'utf8');
test('V0.6 release, cache and build metadata are consistent',async()=>{const [pkg,manifest,index,sw,build]=await Promise.all(['package.json','manifest.webmanifest','index.html','sw.js','scripts/build.js'].map(read));assert.equal(JSON.parse(pkg).version,'0.7.7');assert.equal(JSON.parse(manifest).version,'0.7.7');assert.match(index,/V0\.7\.7(?:-shell-20260811)?/);assert.match(sw,/assessor-plus-v0\.7\.7(?:-shell-20260811)?/);assert.match(build,/V0\.7\.7(?:-shell-20260811)?/)});
test('course data remains identical except for approved display-title metadata and mapping source remains untouched',async()=>{const b=await readFile(new URL('../level3-trowel-6570-05-FULL-course-data.json',import.meta.url));assert.equal(createHash('sha256').update(b).digest('hex'),'9011e445dfb3244710031830efbacb737d5fc190ab15e18042826fd81ce50c23');assert.doesNotMatch(await read('src/evidence.js'),/threshold|similarity/i)});
test('legacy assessments remain readable without invented image signatures',()=>{const a=normaliseAssessment({signature:'Legacy Name'});assert.equal(a.signature,'Legacy Name');assert.equal(a.signatureSnapshot,null);assert.deepEqual(a.knowledgeEvidence,[])});
test('signature is copied and replacement cannot change historical snapshot',()=>{const a={assessor:'',signature:''},p={name:'Pat',signatureDataUrl:'data:image/png;base64,ONE',signatureType:'image/png'};assert.ok(applySignatureSnapshot(a,p,new Date('2026-08-11T12:00:00Z')));p.signatureDataUrl='data:image/png;base64,TWO';assert.match(a.signatureSnapshot.dataUrl,/ONE/);assert.equal(a.assessor,'Pat');assert.equal(a.signatureDate,'2026-08-11');invalidateSignature(a);assert.equal(a.signatureSnapshot,null)});
test('stable practical, audio and document references never reuse removed IDs',()=>{const a={id:'OBS-0001',media:[{reference:'OBS-0001-P01'},{reference:'OBS-0001-P03'},{reference:'OBS-0001-V01'}],knowledgeEvidence:[{reference:'OBS-0001-A01'},{reference:'OBS-0001-DOC01'}]};assert.equal(nextEvidenceReference(a,'photo'),'OBS-0001-P04');assert.equal(nextEvidenceReference(a,'video'),'OBS-0001-V02');assert.equal(nextEvidenceReference(a,'audio'),'OBS-0001-A02');assert.equal(nextEvidenceReference(a,'document'),'OBS-0001-DOC02')});
test('media metadata serializes with the same assessment and matrix remains AC-derived',()=>{const a=normaliseAssessment({id:'OBS-0001',learnerId:'L',primaryUnit:'235',date:'2026-08-11',selected:{practical:['1.1'],knowledge:[]},mappings:{practical:[],knowledge:[]},media:[{id:'p',kind:'photo',reference:'OBS-0001-P01'},{id:'v',kind:'video',reference:'OBS-0001-V01'}],knowledgeEvidence:[{id:'a',kind:'audio',reference:'OBS-0001-A01'},{id:'d',kind:'document',reference:'OBS-0001-DOC01'}]});const reopened=JSON.parse(JSON.stringify(a));assert.equal(reopened.media.length,2);assert.equal(reopened.knowledgeEvidence.length,2);assert.ok(deriveMatrix([a]).has('235.1.1'));a.media=[];a.knowledgeEvidence=[];assert.ok(deriveMatrix([a]).has('235.1.1'))});
test('PDF audit uses assessment signature snapshot and all media references',()=>{const a={id:'OBS-0001',primaryUnit:'235',date:'2026-08-11',assessor:'Pat',selected:{practical:[],knowledge:[]},mappings:{practical:[],knowledge:[]},notes:'',hasDiscussion:true,discussionNotes:'',media:[{kind:'photo',reference:'OBS-0001-P01'},{kind:'video',reference:'OBS-0001-V01'}],knowledgeEvidence:[{kind:'audio',reference:'OBS-0001-A01'},{kind:'document',reference:'OBS-0001-DOC01',name:'notes.pdf'}],signatureSnapshot:{dataUrl:'data:image/png;base64,OLD'},signatureDate:'2026-08-11'};const text=assessmentPdfText(a,{name:'Learner'},{course:{title:'Course'},units:[{id:'235',title:'Unit'}]});for(const x of ['OBS-0001_Video_01.bin','OBS-0001_Audio_01.bin','OBS-0001_Document_01.pdf','Pat'])assert.match(text,new RegExp(x))});
test('storage migration is additive and never deletes or clears stores',async()=>{const storage=await read('src/storage.js');assert.match(storage,/assessor-plus-v01/);assert.doesNotMatch(storage,/deleteDatabase|\.clear\(/);assert.match(storage,/settings/);assert.match(storage,/media/)});

test('material edits invalidate signing while preview URLs do not count',()=>{const old={notes:'one',signatureSnapshot:{dataUrl:'x'},media:[{url:'blob:old'}]};assert.equal(materialAssessmentChanged(old,{...old,media:[{url:'blob:new'}]}),false);assert.equal(materialAssessmentChanged(old,{...old,notes:'two'}),true)});
