import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {assessmentPdfText,evidenceExportFiles,pdfFilename,zipFilename,PHOTO_COLUMNS,PHOTO_ROWS,PHOTOS_PER_PAGE,photoPageCount,photoFit} from '../src/pdf.js';
import {createZip} from '../src/zip.js';

const course=JSON.parse(await readFile('level3-trowel-6570-05-FULL-course-data.json'));
const a={id:'OBS0003',date:'2026-08-11',primaryUnit:'235',assessor:'Historic Assessor',notes:'Observed work.',feedback:'My saved feedback.',signatureDate:'2026-08-11',signatureSnapshot:{assessorName:'Historic Assessor',dataUrl:'data:image/jpeg;base64,/9j/2Q=='},selected:{practical:['1.1'],knowledge:[]},mappings:{practical:[],knowledge:[]},media:[{id:'v1',kind:'video',name:'original.MP4',type:'video/mp4'}],knowledgeEvidence:[{id:'a1',kind:'audio',name:'sound.webm',type:'audio/webm'},{id:'d1',kind:'document',name:'plan.pdf',type:'application/pdf'}]};
const learner={name:'Learner',optionalUnitId:'690'};

test('observation ZIP naming and PDF audit references share the saved reference',()=>{const names=evidenceExportFiles(a).map(x=>x.name);assert.deepEqual(names,['OBS0003_Video_01.mp4','OBS0003_Audio_01.webm','OBS0003_Document_01.pdf']);assert.equal(pdfFilename(a),'OBS0003_Observation.pdf');assert.equal(zipFilename(a),'AssessorPlus_OBS0003.zip');const text=assessmentPdfText(a,learner,course);for(const name of names)assert.match(text,new RegExp(name.replace('.','\\.')))});
test('store-only ZIP retains original video and audio bytes exactly',async()=>{const video=new Uint8Array([0,255,17,4,88]),audio=new Uint8Array([9,8,7,6]),zip=await createZip([{name:'OBS0003_Video_01.mp4',data:video},{name:'OBS0003_Audio_01.webm',data:audio}]),raw=new Uint8Array(await zip.arrayBuffer()),contains=needle=>raw.some((_,i)=>needle.every((v,j)=>raw[i+j]===v));assert.ok(contains(video));assert.ok(contains(audio));assert.equal(zip.type,'application/zip')});
test('photographic evidence uses a contained 3 by 4 grid and paginates at twelve',()=>{assert.equal(PHOTO_COLUMNS,3);assert.equal(PHOTO_ROWS,4);assert.equal(PHOTOS_PER_PAGE,12);assert.equal(photoPageCount(12),1);assert.equal(photoPageCount(13),2);const landscape=photoFit(1600,900,240,100);assert.equal(landscape.rotated,false);assert.ok(landscape.width<=240&&landscape.height<=100);assert.equal(landscape.width/landscape.height,1600/900);const portrait=photoFit(900,1600,240,100);assert.equal(portrait.rotated,true);assert.ok(portrait.width<=240&&portrait.height<=100);assert.equal(portrait.width/portrait.height,1600/900)});
test('PDF is assessor-facing, preserves manual feedback and signature identity, and removes generated/internal prose',()=>{const text=assessmentPdfText(a,learner,course);for(const phrase of ['My saved feedback.','Historic Assessor','11-08-2026','UNIT 235','Observation ACs — 1.1'])assert.match(text,new RegExp(phrase.replace(/[+.]/g,'\\$&')));assert.doesNotMatch(text,/Competent evidence demonstrated|Signature image: assessment snapshot retained|Blob|IndexedDB|mapping-engine/i)});
test('workflow exposes ZIP export and removes generated feedback while retaining its editable field',async()=>{const app=await readFile('src/app.js','utf8');assert.match(app,/Download Evidence ZIP/);assert.match(app,/id=feedback/);assert.match(app,/createZip/);assert.doesNotMatch(app,/data-generate|generateFeedback|Generate from Assessment/)});
test('V0.7.7 offline shell includes the ZIP module and fresh cache',async()=>{const sw=await readFile('sw.js','utf8');assert.match(sw,/assessor-plus-v0\.7\.7(?:-shell-20260811)?/);assert.match(sw,/\.\/src\/zip\.js/)});
