import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {COURSE_FILES,DEFAULT_COURSE_ID,learnerCourseId,courseForLearner,availableUnits,flattenCourse,validateCourse} from '../src/course.js';
import {generateMappings} from '../src/mapping.js';
import {previousEvidenceMatrix} from '../src/observation-evidence.js';
import {deriveUnitProgress} from '../src/progress.js';
import {assessmentPdfText,zipFilename} from '../src/pdf.js';
const l2=JSON.parse(await readFile('level2-trowel-6570-04-FULL-course-data.json'));
const l3=JSON.parse(await readFile('level3-trowel-6570-05-FULL-course-data.json'));
const courses=new Map([[l2.course.id,l2],[l3.course.id,l3]]);
const learner=(course,optionalUnitId,id=course.course.id)=>({id,name:id,courseId:course.course.id,optionalUnitId});
const assessment=(l,courseId=l.courseId)=>({id:`A-${l.id}`,learnerId:l.id,courseId,primaryUnit:'235',date:'2026-08-11',assessor:'A',selected:{practical:['1.1'],knowledge:[]},mappings:{practical:[],knowledge:[]},media:[]});
test('course registry and legacy records resolve only to Level 3',()=>{assert.deepEqual(Object.keys(COURSE_FILES).sort(),[l2.course.id,l3.course.id,'st0095-v1.2-bricklayer','st0171-v1.1-property-maintenance-operative','st0264-v1.4-carpentry-joinery'].sort());assert.equal(learnerCourseId({}),DEFAULT_COURSE_ID);assert.equal(courseForLearner(courses,{}),l3)});
test('both authoritative qualifications validate to their exact independent totals',()=>{assert.deepEqual(validateCourse(l2).counts,{units:11,learningOutcomes:72,criteria:331,practical:126,knowledge:205,ambiguous:0});assert.deepEqual(validateCourse(l3).counts,{units:12,learningOutcomes:75,criteria:335,practical:128,knowledge:207,ambiguous:0})});
test('qualification-specific optional and active units remain independent',()=>{const a=learner(l2,'817'),b=learner(l3,'690');assert.deepEqual(availableUnits(l2,a).map(x=>x.id),[...l2.course.mandatoryUnitIds,'817']);assert.deepEqual(availableUnits(l3,b).map(x=>x.id),[...l3.course.mandatoryUnitIds,'690']);assert.equal(availableUnits(l2,a).length,6);assert.equal(availableUnits(l3,b).length,9)});
test('Practical and Knowledge criteria come only from the selected qualification',()=>{for(const c of [l2,l3]){const rows=flattenCourse(c);assert.equal(rows.filter(x=>x.ac.evidenceClass==='practical').length,c===l2?126:128);assert.equal(rows.filter(x=>x.ac.evidenceClass==='knowledge').length,c===l2?205:207)}});
test('mapping inventories are qualification scoped and thresholds are unchanged',()=>{for(const[c,automatic,confirm]of[[l2,1630,558],[l3,1468,388]]){const mappings=generateMappings(c);assert.equal(mappings.filter(x=>x.mappingType==='automatic').length,automatic);assert.equal(mappings.filter(x=>x.mappingType==='confirm').length,confirm);assert.ok(mappings.every(x=>x.similarity>=.4&&(x.mappingType==='automatic'?x.similarity>=.7:x.similarity<.7)))}});
test('previous evidence and progress reject cross-course and legacy contamination for Level 2',()=>{const l=learner(l2,'234','same'),own=assessment(l),cross={...assessment(l,l3.course.id),id:'cross'},legacy={...assessment(l,undefined),courseId:undefined,id:'legacy'};assert.equal(previousEvidenceMatrix(l2,l,[own,cross,legacy]).get('235.1.1').length,1);assert.equal(deriveUnitProgress(l2,l,[own,cross,legacy]).find(x=>x.unit.id==='235').practical.assessed,1)});
test('PDF and ZIP identify the selected qualification',()=>{for(const[c,opt]of[[l2,'234'],[l3,'690']]){const l=learner(c,opt),a=assessment(l),text=assessmentPdfText(a,l,c);assert.match(text,new RegExp(c.course.qualificationNumber));assert.match(text,/ASSESSOR\+ V0\.8\.1(?:-[a-z0-9-]+)?/);assert.match(zipFilename(a,c),new RegExp(c.course.qualificationNumber))}});
test('offline shell and build include both complete qualification files',async()=>{const [sw,build]=await Promise.all([readFile('sw.js','utf8'),readFile('scripts/build.js','utf8')]);for(const file of Object.values(COURSE_FILES)){assert.match(sw,new RegExp(file));assert.match(build,new RegExp(file))}});
