import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {annualLeaveForDate,collegeDayForDate,learnerAvailability,learnerPlanningStatus,bookingAwareness} from '../src/planning.js';
import {createBackup,validateBackup,APP_VERSION} from '../src/backup.js';

const learner={id:'l1',name:'Ryan Reynolds',annualLeave:[{id:'a',startDate:'2026-08-17',endDate:'2026-08-17'},{id:'b',startDate:'2026-08-24',endDate:'2026-08-28'}],collegeDays:{weekdays:[2,4],dates:['2026-08-21']}};
const stores=l=>({learners:[l],assessments:[],media:[],settings:[],profileAssets:[],professionalDocuments:[],reviews:[],visits:[]});

test('legacy learners have safe empty availability defaults',()=>{assert.deepEqual(learnerAvailability({id:'old'},'2026-08-17'),{annualLeave:[],collegeDay:false,labels:[]});assert.equal(learnerPlanningStatus({id:'old'},[],new Date('2026-08-17T10:00:00Z')),'none')});
test('annual leave supports a single day, ranges, edits and deletes additively',()=>{assert.equal(annualLeaveForDate(learner,'2026-08-17').length,1);assert.equal(annualLeaveForDate(learner,'2026-08-26')[0].id,'b');const edited={...learner,annualLeave:learner.annualLeave.map(x=>x.id==='b'?{...x,endDate:'2026-08-29'}:x)};assert.equal(annualLeaveForDate(edited,'2026-08-29').length,1);assert.equal(annualLeaveForDate({...edited,annualLeave:edited.annualLeave.filter(x=>x.id!=='b')},'2026-08-29').length,0)});
test('college recurring weekdays, multiple days and one-off dates are planning information',()=>{assert.equal(collegeDayForDate(learner,'2026-08-18'),true);assert.equal(collegeDayForDate(learner,'2026-08-20'),true);assert.equal(collegeDayForDate(learner,'2026-08-21'),true);assert.equal(collegeDayForDate(learner,'2026-08-19'),false)});
test('booking awareness reports selected availability and other learners without blocking',()=>{const visits=[{id:'v1',learnerId:'l1',date:'2026-08-24',time:'09:30',type:'review'},{id:'v2',learnerId:'l2',date:'2026-08-24',time:'13:00',type:'observation'}],info=bookingAwareness(learner,'2026-08-24',visits,[learner,{id:'l2',name:'Brad Pitt'}]);assert.equal(info.availability.labels[0],'Annual Leave');assert.equal(info.selectedVisits.length,1);assert.equal(info.otherVisits[0].learner.name,'Brad Pitt');assert.equal(info.hasClash,true)});
test('annual leave today takes priority, otherwise nearest upcoming visit determines status',()=>{const visits=[{id:'v',learnerId:'l1',date:'2026-08-20',time:'09:00',type:'combined',status:'planned'}];assert.equal(learnerPlanningStatus(learner,visits,new Date('2026-08-17T10:00:00Z')),'annual-leave');assert.equal(learnerPlanningStatus(learner,visits,new Date('2026-08-18T10:00:00Z')),'combined');for(const type of ['review','observation','combined','catchup'])assert.equal(learnerPlanningStatus({...learner,annualLeave:[]},[{...visits[0],type}],new Date('2026-08-18T10:00:00Z')),type)});
test('availability round trips automatically in complete backup and older records remain accepted',async()=>{const result=await createBackup(stores(learner),{createdAt:'2026-08-12T12:00:00Z'}),restored=await validateBackup(result.blob);assert.equal(APP_VERSION,'0.8.0');assert.deepEqual(restored.data.learners[0],learner);const old=await createBackup(stores({id:'old',name:'Existing'}),{appVersion:'0.7.10'});assert.equal((await validateBackup(old.blob)).data.learners[0].annualLeave,undefined)});
test('V0.8.0 UI has compact semantic key, status dots, availability, accessible visit icons and install only in Tools',async()=>{const [app,css,html]=await Promise.all(['src/app.js','styles.css','index.html'].map(x=>readFile(x,'utf8')));assert.doesNotMatch(html,/id="install-app"/);assert.match(app,/App & Device/);assert.match(app,/id=install-app/);assert.doesNotMatch(app,/planning-key[\s\S]{0,300}Annual Leave/);assert.doesNotMatch(app,/planning-key[\s\S]{0,500}<i class=/);assert.match(css,/\.planning-key span/);assert.match(css,/\.status-dot/);assert.match(css,/\.status-dot\.annual-leave/);assert.match(css,/\.availability-chip\.yellow/);assert.match(css,/\.availability-chip\.grey/);assert.match(app,/aria-label="Directions for/);assert.match(app,/aria-label="Go to review for/);assert.match(app,/aria-label="View learner/);assert.match(app,/aria-label="Edit visit/);assert.match(app,/l\?\.name\|\|'Unknown learner'/);assert.match(app,/googleMapsUrl\(v\.location\)/);assert.match(app,/Clash warning/)});
