import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {validateCourse,COURSE_FILES,DEFAULT_COURSE_ID,learnerCourseId,courseForLearner,flattenKSBs} from '../src/course.js';
import {deriveKsbProgress} from '../src/progress.js';
import {previousKsbEvidence} from '../src/observation-evidence.js';
import {assessmentPdfText,evidenceExportFiles} from '../src/pdf.js';
const read=p=>readFile(new URL('../'+p,import.meta.url),'utf8');
const course=JSON.parse(await read('bricklayer-st0095-v1.2-course-data.json'));
const learner={id:'bricklayer-1',name:'Sam',courseId:course.course.id};
const observation=(id='OBS-1',selectedKSBs=['S1','S2','B1'])=>({id,learnerId:learner.id,courseId:course.course.id,primaryUnit:'KSB',date:'2026-08-11',assessor:'Pat',selectedKSBs,notes:'Observed work',feedback:'Saved manual feedback',media:[],knowledgeEvidence:[]});
test('ST0095 identity, counts, references and authoritative wording validate',()=>{assert.deepEqual(course.course,{id:'st0095-v1.2-bricklayer',courseId:'st0095-v1.2-bricklayer',courseType:'KSB',title:'Bricklayer - ST0095 - Version 1.2 - Level 2',reference:'ST0095',version:'1.2',level:2,typicalDurationMonths:24});assert.deepEqual(validateCourse(course),{valid:true,counts:{knowledge:31,skills:22,behaviours:6,total:59},errors:[]});assert.equal(flattenKSBs(course).length,59);assert.deepEqual(course.knowledge.map(x=>x.reference),Array.from({length:31},(_,i)=>`K${i+1}`));assert.deepEqual(course.skills.map(x=>x.reference),Array.from({length:22},(_,i)=>`S${i+1}`));assert.deepEqual(course.behaviours.map(x=>x.reference),Array.from({length:6},(_,i)=>`B${i+1}`));assert.equal(course.knowledge[0].wording,'Awareness of health and safety regulations, standards, and guidance and impact on role. Control of Substances Hazardous to Health (CoSHH). Fire safety. Health and Safety at Work Act. Asbestos awareness. Manual handling. signage, fire extinguishers. Safety signage. Situational awareness. Slips, trips, and falls. Working in confined spaces. Working at height. Electrical safety respiratory protective equipment (RPE), dust suppression.')});
test('registry adds ST0095 while legacy remains exclusively Level 3',()=>{assert.equal(COURSE_FILES[course.course.id],'bricklayer-st0095-v1.2-course-data.json');assert.equal(learnerCourseId({}),DEFAULT_COURSE_ID);const l3={course:{id:DEFAULT_COURSE_ID}},courses=new Map([[DEFAULT_COURSE_ID,l3],[course.course.id,course]]);assert.equal(courseForLearner(courses,{}),l3);assert.equal(courseForLearner(courses,learner),course)});
test('KSB progress and prior evidence are learner and course scoped without Knowledge auto-award',()=>{const own=observation(),otherLearner={...observation('OTHER'),learnerId:'other',selectedKSBs:['S3','B2']},otherCourse={...observation('NVQ'),courseId:DEFAULT_COURSE_ID,selectedKSBs:['S4']};assert.deepEqual(deriveKsbProgress(course,learner,[own,otherLearner,otherCourse]),{knowledge:{assessed:0,total:31},skills:{assessed:2,total:22},behaviours:{assessed:1,total:6},overall:{assessed:3,total:59}});const previous=previousKsbEvidence(course,learner,[own,otherLearner,otherCourse]);assert.equal(previous.get('S1')[0].assessmentId,'OBS-1');assert.equal(previous.has('S3'),false);assert.equal(previous.has('K1'),false)});
test('KSB PDF is authoritative, manual and free of NVQ and EPA pass terminology',()=>{const text=assessmentPdfText(observation(),learner,course);for(const value of ['HOLISTIC OBSERVATION','Bricklayer','ST0095','Version 1.2','Level 2','PRACTICAL EVIDENCE','S1 - Comply with health and safety regulations, standards, and guidance.','Behaviours demonstrated','B1 - Put health, safety and wellbeing first.','Saved manual feedback'])assert.match(text,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(text,/Assessment Criteria|Primary Unit|EPA pass/i)});
test('KSB attachment export preserves observation-reference filenames and original metadata',()=>{const a=observation();a.media=[{id:'v',kind:'video',name:'clip.mp4',type:'video/mp4'}];a.knowledgeEvidence=[{id:'a',kind:'audio',name:'voice.webm',type:'audio/webm'},{id:'d',kind:'document',name:'plan.pdf',type:'application/pdf'}];assert.deepEqual(evidenceExportFiles(a).map(x=>x.name),['OBS-1_Video_01.mp4','OBS-1_Audio_01.webm','OBS-1_Document_01.pdf'])});
test('NVQ authoritative content changes only approved title metadata',()=>{for(const file of ['level2-trowel-6570-04-FULL-course-data.json','level3-trowel-6570-05-FULL-course-data.json']){const current=JSON.parse(execFileSync('cat',[file],{encoding:'utf8'})),original=JSON.parse(execFileSync('git',['show',`HEAD:${file}`],{encoding:'utf8'}));current.course.title=original.course.title;assert.deepEqual(current,original)}});
test('V0.7.10 UI, offline inventory and build package include KSB support',async()=>{const [app,sw,build,pkg,manifest,index]=await Promise.all(['src/app.js','sw.js','scripts/build.js','package.json','manifest.webmanifest','index.html'].map(read));assert.match(app,/data-optional-unit.*hidden/);assert.match(app,/data-ksb/);assert.match(app,/selected\?'selected':entries\.length\?'previously-evidenced'/);for(const source of [sw,build])assert.match(source,/bricklayer-st0095-v1\.2-course-data\.json/);assert.match(sw,/const CACHE='assessor-plus-v0\.7\.10(?:-[a-z0-9-]+)?'/);assert.equal(JSON.parse(pkg).version,'0.7.10');assert.equal(JSON.parse(manifest).version,'0.7.10');assert.match(index,/V0\.7\.10(?:-[a-z0-9-]+)?/)})
