import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {VISIT_TYPES,learnerInitials,upcomingVisits,visitsForLearner,visitsForDate,visitsForWeek,latestCompletedReview,activeLearners,courseOverview,nextVisit} from '../src/planning.js';

test('V0.7.11 navigation is exactly Home, Learners, Planning and Tools while observations remain learner scoped',async()=>{const html=await readFile('index.html','utf8'),app=await readFile('src/app.js','utf8');assert.deepEqual([...html.match(/<nav class="bottom-nav"[\s\S]*?<\/nav>/)[0].matchAll(/>([^<>]+)<\/button>/g)].map(x=>x[1]),['Home','Learners','Planning','Tools']);assert.doesNotMatch(html,/>Assessments</);assert.match(app,/New Observation/);assert.match(app,/data-history/)});
test('visit types have intentional colours and initials are correct',()=>{assert.equal(VISIT_TYPES.review.colour,'blue');assert.equal(VISIT_TYPES.observation.colour,'red');assert.equal(VISIT_TYPES.combined.colour,'purple');assert.equal(learnerInitials('Ryan Reynolds'),'RR');assert.equal(learnerInitials('  Cher '),'C')});
test('planning selectors retain one learner-scoped combined visit and filter chronologically',()=>{const visits=[{id:'2',learnerId:'b',date:'2026-08-12',time:'11:00',type:'review'},{id:'1',learnerId:'a',date:'2026-08-11',time:'10:00',type:'combined'}],now=new Date('2026-08-10T00:00:00Z');assert.equal(visitsForLearner(visits,'a').length,1);assert.equal(visitsForLearner(visits,'a')[0].type,'combined');assert.deepEqual(upcomingVisits(visits,now).map(v=>v.id),['1','2']);assert.equal(visitsForDate(visits,'2026-08-11').length,1);assert.equal(visitsForWeek(visits,new Date('2026-08-11T00:00:00Z')).length,2)});
test('latest review lookup only returns newest completed review and supports no-review state',()=>{const rows=[{id:'draft',learnerId:'a',reviewDate:'2026-09-01',status:'Draft'},{id:'old',learnerId:'a',reviewDate:'2026-01-01',status:'Completed'},{id:'new',learnerId:'a',reviewDate:'2026-07-01',status:'Completed'}];assert.equal(latestCompletedReview(rows,'a').id,'new');assert.equal(latestCompletedReview(rows,'none'),null)});
test('Home selectors count active learners, dynamic courses and next visit',()=>{const learners=[{id:'a',courseId:'x'},{id:'b',courseId:'y'},{id:'c',courseId:'x',status:'withdrawn'}],courses=new Map([['x',{course:{title:'X'}}],['y',{course:{title:'Y'}}]]),visits=[{id:'v',learnerId:'a',date:'2026-08-11',time:'10:00',type:'review'}];assert.equal(activeLearners(learners).length,2);assert.deepEqual(courseOverview(learners,courses).map(x=>[x.title,x.count]),[['X',1],['Y',1]]);assert.equal(nextVisit(visits,new Date('2026-08-10T00:00:00Z')).id,'v')});
test('upgrade shell, reviews, workplace and Professional Discussion defaults are present',async()=>{const [app,storage,sw]=await Promise.all(['src/app.js','src/storage.js','sw.js'].map(x=>readFile(x,'utf8')));assert.match(storage,/upgradeMissingStores/);assert.match(storage,/visits:'id'/);assert.match(app,/workplace/);assert.match(app,/reviewSummary\(l\)/);assert.match(app,/latestCompletedReview/);assert.match(app,/hasDiscussion:true/);assert.equal((app.match(/function knowledgeRows/g)||[]).length,1);assert.match(sw,/assessor-plus-v0\.7\.11-[a-z0-9-]+/);assert.match(sw,/src\/planning\.js/);assert.match(sw,/await fetch\(freshRequest\)/)});
