import test from 'node:test';
import assert from 'node:assert/strict';
import {BACKUP_FORMAT,BACKUP_SCHEMA_VERSION,APP_VERSION,STORE_NAMES,createBackup,validateBackup,restoreBackup,backupCounts,reminderState} from '../src/backup.js';
import {readZip,createZip} from '../src/zip.js';
import {VIDEO_BITS_PER_SECOND,AUDIO_BITS_PER_SECOND,PHOTO_MAX_EDGE,supportedRecorderOptions,videoConstraints,audioConstraints,optimisePhoto} from '../src/media.js';

const bytes=async b=>[...new Uint8Array(await b.arrayBuffer())];
function dataset(){return{learners:[{id:'l1',name:'Active',status:'active',courseId:'course-a',optionalUnitId:'u1',pathwayId:'p1',workplace:'Site'},{id:'l2',name:'Withdrawn',status:'withdrawn',courseId:'course-b'}],assessments:[{id:'a1',learnerId:'l1',media:[{id:'photo'}],knowledgeEvidence:[{id:'audio'}]}],media:[{id:'photo',assessmentId:'a1',blob:new Blob([[1,2,3]],{type:'image/jpeg'})},{id:'video',assessmentId:'a1',blob:new Blob([[4,5]],{type:'video/webm'})},{id:'audio',assessmentId:'a1',blob:new Blob([[6]],{type:'audio/webm'})},{id:'file',assessmentId:'a1',blob:new Blob([[7,8]],{type:'application/pdf'})}],settings:[{key:'assessor-profile',name:'Assessor',providerName:'College',backupReminder:'monthly'}],profileAssets:[{key:'signature',blob:new Blob([[9]],{type:'image/png'})},{key:'provider-logo',blob:new Blob([[10]],{type:'image/png'})}],professionalDocuments:[{id:'doc',name:'Certificate',blob:new Blob([[11]],{type:'application/pdf'})}],reviews:[{id:'r1',learnerId:'l1',history:[{action:'target'}]}],visits:[{id:'v1',learnerId:'l1',note:'visit'}]}}

test('complete inventory, manifest and binary round trip restore current schema',async()=>{const original=dataset(),createdAt='2026-08-11T14:35:00.000Z',result=await createBackup(original,{createdAt});assert.deepEqual(STORE_NAMES,['learners','assessments','media','settings','profileAssets','professionalDocuments','reviews','visits']);assert.equal(result.manifest.format,BACKUP_FORMAT);assert.equal(result.manifest.backupSchemaVersion,1);assert.equal(result.manifest.applicationVersion,APP_VERSION);assert.deepEqual(result.manifest.counts,{activeLearners:1,withdrawnLearners:1,reviews:1,observations:1,planningVisits:1,mediaFiles:7});assert.match(result.filename,/AssessorPlus-Backup-20260811-1435\.zip/);const files=await readZip(result.blob);for(const name of STORE_NAMES)assert.ok(files.has(`data/${name}.json`));assert.equal([...files.keys()].filter(x=>x.startsWith('media/')).length,7);const restored=await validateBackup(result.blob);assert.deepEqual(restored.data.learners,original.learners);assert.deepEqual(restored.data.reviews,original.reviews);assert.deepEqual(restored.data.visits,original.visits);for(let i=0;i<original.media.length;i++)assert.deepEqual(await bytes(restored.data.media[i].blob),await bytes(original.media[i].blob));assert.deepEqual(backupCounts(restored.data),result.manifest.counts);await assert.rejects(()=>restoreBackup(restored),/Explicit replacement/)});

test('corrupt, invalid, unsupported and missing attachment backups reject before restore',async()=>{await assert.rejects(()=>validateBackup(new Blob([[1,2,3]])),/could not be read/);const invalid=await createZip([{name:'manifest.json',data:new TextEncoder().encode('{}')}]);await assert.rejects(()=>validateBackup(invalid),/recognised/);const original=dataset(),valid=await createBackup(original),files=await readZip(valid.blob),manifest=JSON.parse(new TextDecoder().decode(files.get('manifest.json')));manifest.backupSchemaVersion=BACKUP_SCHEMA_VERSION+1;const unsupported=await createZip([{name:'manifest.json',data:new TextEncoder().encode(JSON.stringify(manifest))},...[...files].filter(([n])=>n!=='manifest.json').map(([name,data])=>({name,data}))]);await assert.rejects(()=>validateBackup(unsupported),/not supported/);const missing=await createZip([...files].filter(([name])=>!name.startsWith('media/')).map(([name,data])=>({name,data})));await assert.rejects(()=>validateBackup(missing),/missing or corrupt/)});

test('media recorder targets are efficient and codec support degrades gracefully',()=>{class Some{static isTypeSupported(t){return t==='video/webm'}}class None{static isTypeSupported(){return false}}assert.deepEqual(supportedRecorderOptions('video',Some),{mimeType:'video/webm',videoBitsPerSecond:VIDEO_BITS_PER_SECOND,audioBitsPerSecond:AUDIO_BITS_PER_SECOND});assert.deepEqual(supportedRecorderOptions('audio',None),{audioBitsPerSecond:AUDIO_BITS_PER_SECOND});assert.equal(VIDEO_BITS_PER_SECOND,1_400_000);assert.equal(AUDIO_BITS_PER_SECOND,48_000);assert.equal(videoConstraints().video.width.ideal,1280);assert.equal(audioConstraints().audio.channelCount,1)});

test('photo optimisation never upscales and caps large evidence photos',async()=>{const small=new Blob([[1]],{type:'image/jpeg'});small.name='small.jpg';let canvasCalled=false;const same=await optimisePhoto(small,{createBitmap:async()=>({width:800,height:600,close(){}}),createCanvas:()=>{canvasCalled=true}});assert.equal(same,small);assert.equal(canvasCalled,false);assert.equal(PHOTO_MAX_EDGE,1920)});

test('backup reminder defaults weekly, supports monthly/off and session dismissal',()=>{const now=Date.parse('2026-08-11T00:00:00Z');assert.equal(reminderState({backupReminderStartedAt:'2026-08-03T00:00:00Z'},now).due,true);assert.equal(reminderState({backupReminder:'monthly',backupReminderStartedAt:'2026-07-20T00:00:00Z'},now).due,false);assert.equal(reminderState({backupReminder:'off'},now).due,false);assert.equal(reminderState({lastSuccessfulBackup:'2026-08-10T00:00:00Z'},now).due,false);assert.equal(reminderState({backupReminderStartedAt:'2026-08-01T00:00:00Z'},now,true).due,false)});
