import test from 'node:test';import assert from 'node:assert/strict';
import {APP_VERSION,BACKUP_FORMAT,BACKUP_SCHEMA_VERSION,STORE_INVENTORY,createBackup,validateBackup,reminderDue} from '../src/backup.js';
import {readZip,createZip} from '../src/zip.js';
import {AUDIO_BITS_PER_SECOND,VIDEO_BITS_PER_SECOND,MAX_PHOTO_EDGE,recorderOptions,optimisePhoto} from '../src/media.js';
const blob=(text,type)=>new Blob([text],{type});
const dataset=()=>({
 learners:[{id:'active',name:'A',courseId:'level3',optionalUnitId:'837',pathwayId:'',workplace:'Site',status:'active'},{id:'withdrawn',name:'W',courseId:'st0264',pathwayId:'site-carpentry',status:'withdrawn'}],
 assessments:[{id:'OBS-1',learnerId:'active',media:[{id:'photo'}],knowledgeEvidence:[{id:'audio'}],history:['retained'],signatureSnapshot:{dataUrl:'data:image/png;base64,AA=='}}],
 media:[{id:'photo',assessmentId:'OBS-1',blob:blob('photo','image/jpeg')},{id:'video',assessmentId:'OBS-1',blob:blob('video','video/webm')},{id:'audio',assessmentId:'OBS-1',blob:blob('speech','audio/webm')},{id:'file',assessmentId:'OBS-1',blob:blob('document','application/pdf')}],
 settings:[{key:'assessor-profile',name:'Assessor',providerName:'College'},{key:'backup-settings',reminderFrequency:'monthly'}],
 profileAssets:[{key:'signature',blob:blob('signature','image/png')},{key:'provider-logo',blob:blob('logo','image/png')}],professionalDocuments:[{id:'cv',name:'CV',blob:blob('cv','application/pdf')}],
 reviews:[{id:'REV-1',learnerId:'active',targets:[{action:'Do it'}],history:['retained']}],visits:[{id:'VISIT-1',learnerId:'active',note:'Visit note'}]
});
test('complete inventory is explicit and matches every IndexedDB store',()=>assert.deepEqual(STORE_INVENTORY,['learners','assessments','media','settings','profileAssets','professionalDocuments','reviews','visits']));
test('complete portable backup manifest and binary ZIP are deterministic and valid',async()=>{const original=dataset(),result=await createBackup(original,{createdAt:'2026-08-11T14:35:00.000Z'});assert.equal(result.filename,'AssessorPlus-Backup-2026-08-11-1435.zip');assert.equal(result.manifest.backupFormat,BACKUP_FORMAT);assert.equal(result.manifest.backupSchemaVersion,1);assert.equal(result.manifest.applicationVersion,APP_VERSION);assert.deepEqual(result.manifest.counts,{activeLearners:1,withdrawnLearners:1,reviews:1,observations:1,planningVisits:1,mediaFiles:7});const files=await readZip(result.blob);assert(files.has('manifest.json'));assert(files.has('data/stores.json'));assert.equal([...files.keys()].filter(x=>x.startsWith('media/')).length,7)});
test('round trip to fresh storage preserves records, IDs, history, settings and exact media bytes',async()=>{const original=dataset(),{data}=await validateBackup((await createBackup(original)).blob);for(const store of STORE_INVENTORY)assert.equal(data[store].length,original[store].length);assert.equal(data.learners[0].courseId,'level3');assert.equal(data.learners[0].optionalUnitId,'837');assert.equal(data.learners[1].pathwayId,'site-carpentry');assert.deepEqual(data.reviews[0].history,['retained']);assert.equal(data.visits[0].note,'Visit note');assert.equal(data.settings[0].providerName,'College');for(const store of ['media','profileAssets','professionalDocuments'])for(let i=0;i<data[store].length;i++)assert.deepEqual(new Uint8Array(await data[store][i].blob.arrayBuffer()),new Uint8Array(await original[store][i].blob.arrayBuffer()))});
test('corrupt ZIP, invalid manifest, unsupported schema and missing media are rejected before replacement',async()=>{await assert.rejects(validateBackup(new Uint8Array([1,2,3])),/complete Assessor/);const bad=async manifest=>createZip([{name:'manifest.json',data:new TextEncoder().encode(JSON.stringify(manifest))},{name:'data/stores.json',data:new TextEncoder().encode(JSON.stringify(Object.fromEntries(STORE_INVENTORY.map(s=>[s,[]]))))}]);await assert.rejects(validateBackup(await bad({backupFormat:'wrong',backupSchemaVersion:1,requiredFiles:['data/stores.json']})),/recognised/);await assert.rejects(validateBackup(await bad({backupFormat:BACKUP_FORMAT,backupSchemaVersion:99,requiredFiles:['data/stores.json']})),/schema/);const result=await createBackup(dataset()),files=await readZip(result.blob),missing=[...files].filter(([name])=>name!=='media/media/photo.bin').map(([name,data])=>({name,data}));await assert.rejects(validateBackup(await createZip(missing)),/required file is missing/)});
test('backup reminder defaults weekly and supports monthly, off and snooze intervals',()=>{const now=Date.parse('2026-08-11T12:00:00Z');assert.equal(reminderDue({reminderStartedAt:'2026-08-03T12:00:00Z'},now),true);assert.equal(reminderDue({frequency:'weekly',lastSuccessfulBackup:'2026-08-05T12:00:00Z'},now),false);assert.equal(reminderDue({frequency:'monthly',lastSuccessfulBackup:'2026-07-10T12:00:00Z'},now),true);assert.equal(reminderDue({frequency:'off',lastSuccessfulBackup:'2020-01-01'},now),false);assert.equal(reminderDue({frequency:'weekly',snoozedAt:'2026-08-10T12:00:00Z'},now),false)});
test('recording preferences target efficient video and speech audio with graceful codec fallback',()=>{class Supported{static isTypeSupported(x){return x.includes('vp8')||x.startsWith('audio/')}}const video=recorderOptions('video',Supported),audio=recorderOptions('audio',Supported);assert.equal(video.videoBitsPerSecond,VIDEO_BITS_PER_SECOND);assert.equal(video.audioBitsPerSecond,64000);assert.match(video.mimeType,/vp8/);assert.equal(audio.audioBitsPerSecond,AUDIO_BITS_PER_SECOND);class None{static isTypeSupported(){return false}}assert.deepEqual(recorderOptions('audio',None),{audioBitsPerSecond:64000});assert.equal(Math.round(VIDEO_BITS_PER_SECOND*60/8/1024/1024),10)});
test('photo optimiser never upscales and leaves existing/small input bytes untouched',async()=>{const file=blob('small','image/jpeg');globalThis.createImageBitmap=async()=>({width:800,height:600,close(){}});assert.equal(await optimisePhoto(file),file);delete globalThis.createImageBitmap;assert.equal(MAX_PHOTO_EDGE,1920)});
