import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {generateMappings} from '../src/mapping.js';import {deriveMatrix,evidencedEntries} from '../src/matrix.js';import {availableUnits} from '../src/course.js';import {assessmentPdfText,makePdf} from '../src/pdf.js';
const course=JSON.parse(await readFile('level3-trowel-6570-05-FULL-course-data.json')),table=generateMappings(course);
const learner={id:'learner-1',name:'Joe Bloggs',courseId:course.course.id,optionalUnitId:'690'};
function record(id='OBS-0001'){const auto=table.find(x=>x.sourceUnit==='235'&&x.sourceAC==='1.1'&&x.targetUnit==='234'&&x.targetAC==='1.1'),confirm=table.find(x=>x.sourceUnit==='235'&&x.mappingType==='confirm');return{id,learnerId:learner.id,primaryUnit:'235',date:'2026-08-11',assessor:'A Assessor',selected:{practical:['1.1'],knowledge:['2.1']},mappings:{practical:[{...auto,decision:'automatic'},...(confirm?[{...confirm,decision:'confirmed'}]:[])],knowledge:[]},notes:'Observed practical activity safely.',hasDiscussion:true,discussionNotes:'Learner explained their response.',media:[{reference:`${id}-P01`,kind:'photo',name:'site.jpg'},{reference:`${id}-V01`,kind:'video',name:'site.mp4'}],outcome:'Competent evidence demonstrated',feedback:'Evidence in this assessment was competent.',signature:'A Assessor',signatureDate:'2026-08-11'};}
test('full persisted workflow record retains assessment fields after serialization',()=>{const units=availableUnits(course,learner);assert.equal(units.length,9);const practical=course.units.find(u=>u.id==='235').learningOutcomes.flatMap(l=>l.criteria).filter(a=>a.evidenceClass==='practical');const knowledge=course.units.find(u=>u.id==='235').learningOutcomes.flatMap(l=>l.criteria).filter(a=>a.evidenceClass==='knowledge');assert.ok(practical.length&&knowledge.length);assert.ok(practical.every(a=>a.evidenceClass==='practical'));assert.ok(knowledge.every(a=>a.evidenceClass==='knowledge'));const reopened=JSON.parse(JSON.stringify(record()));assert.equal(reopened.notes,'Observed practical activity safely.');assert.equal(reopened.discussionNotes,'Learner explained their response.');assert.equal(reopened.signature,'A Assessor');assert.equal(reopened.media.length,2);assert.equal(reopened.outcome,'Competent evidence demonstrated')});
test('automatic and confirmed evidence derive into target units while ignored does not',()=>{const a=record(),possible=table.find(x=>x.sourceUnit==='235'&&x.mappingType==='confirm'&&!a.mappings.practical.some(y=>y.targetUnit===x.targetUnit&&y.targetAC===x.targetAC));if(possible)a.mappings.practical.push({...possible,decision:'ignored'});const m=deriveMatrix([a]);assert.ok(m.get('235.1.1'));assert.ok(m.get('234.1.1').some(e=>e.mappingSource==='AUTOMATIC HOLISTIC MATCH'));assert.ok([...m.values()].flat().some(e=>e.mappingSource==='ASSESSOR-CONFIRMED HOLISTIC MATCH'));assert.ok(![...m.values()].flat().some(e=>e.mappingSource.includes('ignored')))});
test('matrix recalculates removal and retains independent evidence',()=>{const a=record(),b=record('OBS-0007');let m=deriveMatrix([a,b]);assert.equal(m.get('235.1.1').length,2);a.selected.practical=[];a.mappings.practical=[];m=deriveMatrix([a,b]);assert.equal(m.get('235.1.1').length,1);b.selected.practical=[];b.mappings.practical=[];m=deriveMatrix([a,b]);assert.equal(m.has('235.1.1'),false)});
test('PDF content contains assessment, methods, decision, media and mapping audit',()=>{const a=record(),text=assessmentPdfText(a,learner,course);for(const phrase of ['OBS-0001','Joe Bloggs','PRACTICAL OBSERVATION','PROFESSIONAL DISCUSSION','ASSESSMENT DECISION','OBS-0001-P01','AUTOMATIC HOLISTIC MATCH'])assert.ok(text.includes(phrase));assert.ok(makePdf(a,learner,course).size>500)});
test('evidence entries do not duplicate the assessment record',()=>{const a=record();assert.ok(evidencedEntries(a).length>1);assert.equal(a.id,'OBS-0001')});
