import {createZip,readZip} from './zip.js';
export const BACKUP_FORMAT='uk.assessor-plus.portable-backup',BACKUP_SCHEMA_VERSION=1,APP_VERSION='0.7.7';
export const STORE_INVENTORY=['learners','assessments','media','settings','profileAssets','professionalDocuments','reviews','visits'];
const enc=new TextEncoder(),dec=new TextDecoder();
const binaryStores=new Set(['media','profileAssets','professionalDocuments']);
const cleanRecord=(record,path)=>{const copy={...record};if(copy.blob instanceof Blob){copy.blob={__backupBinary:path,type:copy.blob.type,size:copy.blob.size}}return copy};
const counts=data=>({activeLearners:(data.learners||[]).filter(x=>x.status!=='withdrawn').length,withdrawnLearners:(data.learners||[]).filter(x=>x.status==='withdrawn').length,reviews:(data.reviews||[]).length,observations:(data.assessments||[]).length,planningVisits:(data.visits||[]).length,mediaFiles:[...(data.media||[]),...(data.profileAssets||[]),...(data.professionalDocuments||[])].filter(x=>x.blob instanceof Blob).length});
export async function createBackup(data,{createdAt=new Date().toISOString(),appVersion=APP_VERSION}={}){const files=[],serial={};for(const store of STORE_INVENTORY){serial[store]=[];for(const record of data[store]||[]){let path;if(binaryStores.has(store)&&record.blob instanceof Blob){const key=String(record.id??record.key),safe=key.replace(/[^a-zA-Z0-9._-]/g,'_');path=`media/${store}/${safe}.bin`;files.push({name:path,data:record.blob})}serial[store].push(cleanRecord(record,path))}}const dataBytes=enc.encode(JSON.stringify(serial)),manifest={backupFormat:BACKUP_FORMAT,backupSchemaVersion:BACKUP_SCHEMA_VERSION,applicationVersion:appVersion,createdAt,stores:Object.fromEntries(STORE_INVENTORY.map(x=>[x,serial[x].length])),counts:counts(data),requiredFiles:['data/stores.json',...files.map(x=>x.name)],binaryBytes:files.reduce((n,x)=>n+x.data.size,0)};files.unshift({name:'data/stores.json',data:dataBytes});files.unshift({name:'manifest.json',data:enc.encode(JSON.stringify(manifest,null,2))});return {blob:await createZip(files),manifest,filename:`AssessorPlus-Backup-${createdAt.slice(0,16).replace('T','-').replace(':','')}.zip`}}
export async function validateBackup(input){const files=await readZip(input),manifestFile=files.get('manifest.json');if(!manifestFile)throw new Error('Backup manifest is missing.');let manifest;try{manifest=JSON.parse(dec.decode(manifestFile))}catch{throw new Error('Backup manifest is invalid.')}if(manifest.backupFormat!==BACKUP_FORMAT)throw new Error('This is not a recognised Assessor+ backup.');if(manifest.backupSchemaVersion!==BACKUP_SCHEMA_VERSION)throw new Error('This backup schema is not supported by this version of Assessor+.');if(!Array.isArray(manifest.requiredFiles)||!manifest.requiredFiles.every(x=>files.has(x)))throw new Error('Backup is incomplete: a required file is missing.');let data;try{data=JSON.parse(dec.decode(files.get('data/stores.json')))}catch{throw new Error('Backup data is invalid.')}if(STORE_INVENTORY.some(s=>!Array.isArray(data[s])))throw new Error('Backup store inventory is incomplete.');for(const store of STORE_INVENTORY)for(const record of data[store])if(record.blob?.__backupBinary){const bytes=files.get(record.blob.__backupBinary);if(!bytes||bytes.length!==record.blob.size)throw new Error('Backup media is missing or incomplete.');record.blob=new Blob([bytes],{type:record.blob.type})}return {manifest,data,summary:manifest.counts}}
export const reminderDue=({frequency='weekly',lastSuccessfulBackup,reminderStartedAt,snoozedAt},now=Date.now())=>{if(frequency==='off')return false;const origin=Date.parse(lastSuccessfulBackup||snoozedAt||reminderStartedAt||new Date(now).toISOString()),days=frequency==='monthly'?30:7;return now-origin>=days*86400000};
