import {STORES,readAllStores} from './storage.js';
import {replaceAllStores} from './restore-storage.js';
import {createZip,readZip,crc32} from './zip.js';

export const BACKUP_FORMAT='uk.assessorplus.portable-backup',BACKUP_SCHEMA_VERSION=1,APP_VERSION='0.7.8';
export const STORE_NAMES=Object.freeze(Object.keys(STORES));
const encoder=new TextEncoder(),decoder=new TextDecoder();
const json=value=>encoder.encode(JSON.stringify(value,null,2));
const hex=n=>n.toString(16).padStart(8,'0');
const safePart=value=>String(value).replace(/[^a-zA-Z0-9._-]/g,'_');

async function extract(value,path,binaries){if(value instanceof Blob){const bytes=new Uint8Array(await value.arrayBuffer());let name=`media/${path}.bin`,suffix=2;while(binaries.some(file=>file.name===name))name=`media/${path}-${suffix++}.bin`;binaries.push({name,data:bytes});return{$binary:name,type:value.type,size:value.size,crc32:hex(crc32(bytes))}}if(Array.isArray(value))return Promise.all(value.map((item,index)=>extract(item,`${path}-${index}`,binaries)));if(value&&typeof value==='object'){const out={};for(const[key,item]of Object.entries(value))out[key]=await extract(item,key==='blob'?path:`${path}-${safePart(key)}`,binaries);return out}return value}
async function inflate(value,files,seen){if(Array.isArray(value))return Promise.all(value.map(item=>inflate(item,files,seen)));if(value&&typeof value==='object'&&value.$binary){const bytes=files.get(value.$binary);if(!bytes||bytes.length!==value.size||hex(crc32(bytes))!==value.crc32)throw new Error(`Backup attachment is missing or corrupt: ${value.$binary}`);seen.add(value.$binary);return new Blob([bytes],{type:value.type||'application/octet-stream'})}if(value&&typeof value==='object'){const out={};for(const[key,item]of Object.entries(value))out[key]=await inflate(item,files,seen);return out}return value}
export function backupCounts(data){const learners=data.learners||[],media=data.media||[];return{activeLearners:learners.filter(x=>x.status!=='withdrawn').length,withdrawnLearners:learners.filter(x=>x.status==='withdrawn').length,reviews:(data.reviews||[]).length,observations:(data.assessments||[]).length,planningVisits:(data.visits||[]).length,mediaFiles:media.filter(x=>x.blob instanceof Blob||x.blob?.$binary).length+(data.profileAssets||[]).filter(x=>x.blob instanceof Blob||x.blob?.$binary).length+(data.professionalDocuments||[]).filter(x=>x.blob instanceof Blob||x.blob?.$binary).length}}
export async function createBackup(data,{createdAt=new Date().toISOString(),appVersion=APP_VERSION}={}){data??=await readAllStores();for(const name of STORE_NAMES)if(!Array.isArray(data[name]))throw new Error(`Persistent store missing: ${name}`);const binaries=[],serialised={};for(const name of STORE_NAMES)serialised[name]=await Promise.all(data[name].map((record,index)=>extract(record,`${safePart(name)}/${safePart(record?.id??record?.key??index)}`,binaries)));const storesFile={name:'data/stores.json',data:json(serialised)},inventory=Object.fromEntries(STORE_NAMES.map(name=>[name,serialised[name].length])),manifest={format:BACKUP_FORMAT,backupSchemaVersion:BACKUP_SCHEMA_VERSION,applicationVersion:appVersion,createdAt,stores:inventory,counts:backupCounts(serialised),files:[storesFile,...binaries].map(file=>({path:file.name,size:file.data.length,crc32:hex(crc32(file.data))}))};const blob=await createZip([{name:'manifest.json',data:json(manifest)},storesFile,...binaries]);await validateBackup(blob);return{blob,manifest,filename:`AssessorPlus-Backup-${createdAt.slice(0,16).replace(/[-:T]/g,(c)=>c==='T'?'-':'')}.zip`}}
export async function validateBackup(input){let files;try{files=await readZip(input)}catch(error){throw new Error(`Backup ZIP could not be read: ${error.message}`)}const manifestBytes=files.get('manifest.json');if(!manifestBytes)throw new Error('Backup manifest is missing.');let manifest;try{manifest=JSON.parse(decoder.decode(manifestBytes))}catch{throw new Error('Backup manifest is invalid.')}if(manifest.format!==BACKUP_FORMAT)throw new Error('This is not a recognised Assessor+ backup.');if(manifest.backupSchemaVersion!==BACKUP_SCHEMA_VERSION)throw new Error(`Backup schema ${manifest.backupSchemaVersion} is not supported.`);if(!manifest.createdAt||!manifest.applicationVersion||!manifest.counts||!manifest.stores||!Array.isArray(manifest.files))throw new Error('Backup manifest is incomplete.');const declared=new Set(manifest.files.map(entry=>entry.path));if(declared.size!==manifest.files.length||files.size!==declared.size+1||[...files.keys()].some(path=>path!=='manifest.json'&&!declared.has(path)))throw new Error('Backup file inventory does not match the archive.');for(const entry of manifest.files){const content=files.get(entry.path);if(!content||content.length!==entry.size||hex(crc32(content))!==entry.crc32)throw new Error(`Backup file is missing or corrupt: ${entry.path}`)}const content=files.get('data/stores.json');if(!content)throw new Error('Required backup data is missing: stores');let data;try{data=JSON.parse(decoder.decode(content))}catch{throw new Error('Backup store data is invalid.')}for(const name of STORE_NAMES)if(!Array.isArray(data[name])||data[name].length!==manifest.stores[name])throw new Error(`Backup store inventory does not match: ${name}`);if(Object.keys(data).some(name=>!STORE_NAMES.includes(name))||Object.keys(manifest.stores).some(name=>!STORE_NAMES.includes(name)))throw new Error('Backup store inventory is not compatible with this Assessor+ schema.');const seen=new Set(),inflated={};for(const name of STORE_NAMES)inflated[name]=await inflate(data[name],files,seen);const referenced=manifest.files.filter(x=>x.path.startsWith('media/')).map(x=>x.path);if(referenced.some(path=>!seen.has(path)))throw new Error('Backup contains an unreferenced attachment.');const counts=backupCounts(inflated);if(Object.keys(counts).some(key=>counts[key]!==manifest.counts[key]))throw new Error('Backup summary counts do not match its data.');return{manifest,data:inflated,summary:counts}}
export async function restoreBackup(validated,{replace=false}={}){if(!replace)throw new Error('Explicit replacement confirmation is required.');const staged=validated?.data?validated:await validateBackup(validated);await replaceAllStores(staged.data);return staged.summary}
export const REMINDER_INTERVALS={weekly:7*864e5,monthly:30*864e5,off:Infinity};
export function reminderState(settings={},now=Date.now(),sessionDismissed=false){const frequency=settings.backupReminder||'weekly';if(frequency==='off'||sessionDismissed)return{due:false,frequency};const anchor=Date.parse(settings.lastSuccessfulBackup||settings.backupReminderStartedAt||new Date(now).toISOString());const age=Math.max(0,now-anchor);return{due:age>=REMINDER_INTERVALS[frequency],frequency,days:Math.floor(age/864e5)}}
