import {evidencedEntries} from './matrix.js';
import {activeUnitIds} from './progress.js';
import {formatUKDate} from './dates.js';

const enc=new TextEncoder(), A4=[595.28,841.89], teal=[0,.56,.57], charcoal=[.10,.19,.21];
const ascii=s=>String(s??'').normalize('NFKD').replace(/[^\x20-\x7e]/g,' ');
const pdfText=s=>ascii(s).replace(/([()\\])/g,'\\$1');
const bytes=v=>v instanceof Uint8Array?v:new Uint8Array(v);
const concat=parts=>{const size=parts.reduce((n,p)=>n+p.length,0),out=new Uint8Array(size);let at=0;for(const p of parts){out.set(p,at);at+=p.length}return out};
const extension=m=>{const fromName=(m.name||'').match(/\.([a-z0-9]+)$/i)?.[1];return fromName||({'video/webm':'webm','video/mp4':'mp4','audio/webm':'webm','audio/mp4':'m4a','application/pdf':'pdf'}[m.type]||'bin')};
const evidenceSuffix=ref=>ref?.split('-').at(-1)||'';

export function assessmentPdfText(a,learner,course){
  const unit=course.units.find(u=>u.id===a.primaryUnit)||{id:a.primaryUnit,title:''},active=activeUnitIds(course,learner);
  const lines=['ASSESSOR+ V0.6.1','ASSESSMENT / OBSERVATION RECORD',`Assessment reference: ${a.id}`,`Learner: ${learner.name}`,`Qualification: ${course.course.title}`,`Primary Unit: ${unit.id} - ${unit.title}`,`Assessment date: ${formatUKDate(a.date)}`,`Assessor: ${a.signatureSnapshot?.assessorName||a.assessor}`,a.signatureSnapshot?.providerName?`Provider: ${a.signatureSnapshot.providerName}`:'','PRACTICAL OBSERVATION',a.notes||'No observation narrative recorded.'];
  for(const m of a.media||[])lines.push(`${m.reference} - ${m.kind==='photo'?'Photograph - Embedded visually':'VIDEO EVIDENCE - PDF attachment'} - ${formatUKDate(m.createdAt)}`);
  if(a.hasDiscussion)lines.push('PROFESSIONAL DISCUSSION',a.discussionNotes||'No discussion narrative recorded.',...(a.knowledgeEvidence||[]).map(m=>`${m.reference} - ${m.kind==='audio'?'AUDIO EVIDENCE':'SUPPORTING FILE'} - PDF attachment - ${formatUKDate(m.createdAt)}`));
  lines.push('EVIDENCE SUMMARY',...(a.media||[]).map(m=>`${evidenceSuffix(m.reference)} | ${m.kind==='photo'?'Photograph | Embedded visually':'Video | PDF attachment'}`),...(a.knowledgeEvidence||[]).map(m=>`${evidenceSuffix(m.reference)} | ${m.kind==='audio'?'Audio':'Supporting file'} | PDF attachment`),'Video, audio and supporting files are embedded as attachments within this PDF. Availability of embedded attachments depends on the PDF viewer.','ASSESSMENT CRITERIA EVIDENCED');
  const entries=evidencedEntries(a).filter(e=>active.has(e.unit));
  for(const uid of [...new Set(entries.map(e=>e.unit))]){const u=course.units.find(x=>x.id===uid);lines.push(`UNIT ${uid} - Unit ${uid} - ${u?.title||''}`,uid===a.primaryUnit?'PRIMARY OBSERVATION':'HOLISTIC EVIDENCE',...entries.filter(e=>e.unit===uid).map(e=>`${uid}-AC${e.ac} | ${e.method==='practical'?'Observation':'Professional Discussion'} | ${e.mappingSource}`));}
  lines.push('ASSESSOR FEEDBACK',a.feedback||'No assessor feedback recorded.','ASSESSMENT DECISION',a.outcome||'Not recorded',a.signatureSnapshot?'Signature image: assessment snapshot retained':`Legacy signature: ${a.signature||'Not signed'}`,`Assessor name: ${a.signatureSnapshot?.assessorName||a.assessor||''}`,`Date signed: ${formatUKDate(a.signatureDate)}`);
  return lines.filter(Boolean).join('\n');
}

function simplePdf(text){const lines=text.split('\n').flatMap(x=>ascii(x).match(/.{1,88}(?:\s|$)|.{1,88}/g)||['']),chunks=[];while(lines.length)chunks.push(lines.splice(0,48));const objects=[],font=()=>objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');const fontId=font()||1,pagesId=objects.push('PAGES'),pageIds=[];for(const [pi,page] of chunks.entries()){let stream='0.10 0.19 0.21 rg BT /F1 9 Tf 42 780 Td 14 TL ';for(const line of page)stream+=`(${pdfText(line.trim())}) Tj T* `;stream+=`ET BT /F1 8 Tf 42 24 Td (${pdfText(`Assessment reference | Page ${pi+1} of ${chunks.length}`)}) Tj ET`;const content=objects.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`),pageId=objects.push(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${content} 0 R >>`);pageIds.push(pageId)}objects[pagesId-1]=`<< /Type /Pages /Kids [${pageIds.map(x=>x+' 0 R').join(' ')}] /Count ${pageIds.length} >>`;const catalog=objects.push(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);return serialise(objects,catalog)}
export function makePdf(a,learner,course){return new Blob([simplePdf(assessmentPdfText(a,learner,course))],{type:'application/pdf'})}

function serialise(objects,root){const parts=[enc.encode('%PDF-1.7\n% Assessor+ offline document\n')],offsets=[0];let length=parts[0].length;objects.forEach((obj,i)=>{offsets.push(length);const body=typeof obj==='string'?enc.encode(obj):obj,part=concat([enc.encode(`${i+1} 0 obj\n`),body,enc.encode('\nendobj\n')]);parts.push(part);length+=part.length});const xref=length;let tail=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(const off of offsets.slice(1))tail+=`${String(off).padStart(10,'0')} 00000 n \n`;tail+=`trailer << /Size ${objects.length+1} /Root ${root} 0 R >>\nstartxref\n${xref}\n%%EOF`;parts.push(enc.encode(tail));return concat(parts)}

function jpegSize(data){for(let i=2;i<data.length-9;){if(data[i]!==0xff){i++;continue}const marker=data[i+1],length=(data[i+2]<<8)+data[i+3];if(marker>=0xc0&&marker<=0xc3)return{height:(data[i+5]<<8)+data[i+6],width:(data[i+7]<<8)+data[i+8]};i+=2+length}return{width:800,height:450}}
async function imageJpeg(blob){if(!blob)return null;if(blob.type==='image/jpeg'){const data=bytes(await blob.arrayBuffer());return{data,...jpegSize(data)}}if(typeof createImageBitmap==='undefined')return null;const bitmap=await createImageBitmap(blob),canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0);const converted=await new Promise(r=>canvas.toBlob(r,'image/jpeg',.86));return{data:bytes(await converted.arrayBuffer()),width:canvas.width,height:canvas.height}}

/** Rich offline PDF. assetResolver receives (store, key) and must return the authoritative IndexedDB record. */
export async function makeProfessionalPdf(a,learner,course,{assetResolver=async()=>null,profile={}}={}){
  const objects=[],add=o=>(objects.push(o),objects.length),font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'),bold=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>'),pagesId=add('PAGES'),pages=[];
  const attachments=[];for(const m of [...(a.media||[]),...(a.knowledgeEvidence||[])])if(m.kind!=='photo'){const record=await assetResolver('media',m.id);if(record?.blob)attachments.push({meta:m,data:bytes(await record.blob.arrayBuffer()),name:`${m.reference}.${extension(m)}`})}
  const images=new Map();for(const m of (a.media||[]).filter(x=>x.kind==='photo')){const record=await assetResolver('media',m.id),data=await imageJpeg(record?.blob);if(data)images.set(m.id,data)}
  const logoRecord=await assetResolver('profileAssets','provider-logo'),logo=await imageJpeg(logoRecord?.blob);
  const dataUrl=a.signatureSnapshot?.dataUrl;let signature=null;if(dataUrl?.includes(',')){const raw=atob(dataUrl.split(',')[1]),arr=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)arr[i]=raw.charCodeAt(i);signature=await imageJpeg(new Blob([arr],{type:a.signatureSnapshot.type||'image/png'}))}
  const imageObj=image=>add(concat([enc.encode(`<< /Type /XObject /Subtype /Image /Width ${image.width} /Height ${image.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${image.data.length} >>\nstream\n`),image.data,enc.encode('\nendstream')]));
  const logoId=logo?imageObj(logo):null,sigId=signature?imageObj(signature):null,photoIds=new Map([...images].map(([id,data])=>[id,imageObj(data)]));
  const text=assessmentPdfText(a,learner,course),sections=text.split('\n'),contentPages=[];let current=[];for(const line of sections){const wrapped=ascii(line).match(/.{1,86}(?:\s|$)|.{1,86}/g)||[''];if(current.length+wrapped.length>43){contentPages.push(current);current=[]}current.push(...wrapped)}if(current.length)contentPages.push(current);
  const photoList=(a.media||[]).filter(x=>photoIds.has(x.id));for(let i=0;i<photoList.length;i+=4)contentPages.push(photoList.slice(i,i+4));
  const total=contentPages.length;contentPages.forEach((items,index)=>{let stream='';for(let n=0;n<22;n++){const alpha=(22-n)/22*.10;stream+=`${(.83+alpha).toFixed(3)} ${(1-alpha/3).toFixed(3)} ${(1-alpha/3).toFixed(3)} rg 0 ${842-n*5} ${400-n*10} 6 re f\n`}stream+='0.10 0.19 0.21 rg ';const resources=[];
    if(index===0&&logoId){stream+=`q 110 0 0 62 430 752 cm /Logo Do Q\n`;resources.push(`/Logo ${logoId} 0 R`)}
    if(typeof items[0]==='object'){items.forEach((m,i)=>{const x=i%2?310:42,y=i<2?500:245;stream+=`0.94 0.98 0.98 rg ${x} ${y} 243 180 re f q 243 0 0 137 ${x} ${y+32} cm /P${i} Do Q BT /F2 9 Tf ${x} ${y+16} Td (${pdfText(m.reference)}  ${pdfText(formatUKDate(m.createdAt))}) Tj ET\n`;resources.push(`/P${i} ${photoIds.get(m.id)} 0 R`)})}else{stream+='BT /F1 9 Tf 42 770 Td 15 TL ';items.forEach((line,i)=>{const heading=/^[A-Z][A-Z +/]+$|^UNIT \d+/.test(line);if(heading)stream+=`/F2 ${i<2?15:11} Tf 0.00 0.45 0.47 rg `;else stream+='/F1 9 Tf 0.10 0.19 0.21 rg ';stream+=`(${pdfText(line)}) Tj T* `});stream+='ET\n'}
    if(index===total-1&&sigId){stream+=`q 150 0 0 55 42 55 cm /Sig Do Q\n`;resources.push(`/Sig ${sigId} 0 R`)}stream+=`BT /F1 8 Tf 0.28 0.39 0.40 rg 42 22 Td (${pdfText(`${a.id}  |  Page ${index+1} of ${total}`)}) Tj ET`;const content=add(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`),page=add(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${A4.join(' ')}] /Resources << /Font << /F1 ${font} 0 R /F2 ${bold} 0 R >> /XObject << ${resources.join(' ')} >> >> /Contents ${content} 0 R >>`);pages.push(page)});
  objects[pagesId-1]=`<< /Type /Pages /Kids [${pages.map(x=>x+' 0 R').join(' ')}] /Count ${pages.length} >>`;
  const fileSpecs=[];for(const file of attachments){const embedded=add(concat([enc.encode(`<< /Type /EmbeddedFile /Subtype /${file.meta.type?.replace('/','#2F')||'application#2Foctet-stream'} /Length ${file.data.length} >>\nstream\n`),file.data,enc.encode('\nendstream')]));fileSpecs.push([file.name,add(`<< /Type /Filespec /F (${pdfText(file.name)}) /UF (${pdfText(file.name)}) /EF << /F ${embedded} 0 R >> /Desc (${pdfText(file.meta.reference)} original evidence) >>`)])}
  const names=fileSpecs.length?add(`<< /Names [${fileSpecs.map(([name,id])=>`(${pdfText(name)}) ${id} 0 R`).join(' ')}] >>`):null,catalog=add(`<< /Type /Catalog /Pages ${pagesId} 0 R${names?` /Names << /EmbeddedFiles ${names} 0 R >> /PageMode /UseAttachments`:''} >>`);
  return new Blob([serialise(objects,catalog)],{type:'application/pdf'});
}

export const attachmentBytes=a=>[...(a.media||[]),...(a.knowledgeEvidence||[])].filter(x=>x.kind!=='photo').reduce((n,x)=>n+(x.size||0),0);
export function pdfFilename(a,learner){const safe=s=>ascii(s).trim().replace(/[^a-z0-9.-]+/gi,'-').replace(/^-|-$/g,'');return `AssessorPlus_${safe(learner.name)}_${safe(a.id)}_${formatUKDate(a.date)}.pdf`}
