import {learnerCourseId} from './course.js';

export const VISIT_TYPES={review:{label:'Review',colour:'blue'},observation:{label:'Observation',colour:'red'},combined:{label:'Review + Observation',colour:'purple'},catchup:{label:'Catch-up Review',colour:'amber'}};
export const learnerInitials=name=>String(name||'').trim().split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0].toUpperCase()).join('');
export const shortLearnerName=name=>{const parts=String(name||'').trim().split(/\s+/).filter(Boolean);return parts.length>1?`${parts[0]} ${parts.at(-1)[0]}.`:parts[0]||''};
export const visitDateTime=visit=>`${visit?.date||''}T${visit?.time||'00:00'}`;
export const upcomingVisits=(visits,now=new Date())=>(Array.isArray(visits)?visits:[]).filter(v=>v&&VISIT_TYPES[v.type]&&v.date&&v.status!=='completed'&&visitDateTime(v)>=now.toISOString().slice(0,16)).sort((a,b)=>visitDateTime(a).localeCompare(visitDateTime(b))||String(a.id||'').localeCompare(String(b.id||'')));
export const visitsForLearner=(visits,learnerId)=>(Array.isArray(visits)?visits:[]).filter(v=>v?.learnerId===learnerId);
export const visitsForDate=(visits,date)=>(Array.isArray(visits)?visits:[]).filter(v=>v?.date===date);
export const annualLeaveForDate=(learner,date)=>(Array.isArray(learner?.annualLeave)?learner.annualLeave:[]).filter(x=>x?.startDate&&x.startDate<=date&&(x.endDate||x.startDate)>=date);
export const collegeDayForDate=(learner,date)=>{if(!date)return false;const college=learner?.collegeDays||{},weekday=new Date(`${date}T12:00:00`).getDay();return (Array.isArray(college.weekdays)&&college.weekdays.includes(weekday))||(Array.isArray(college.dates)&&college.dates.includes(date))};
export function learnerAvailability(learner,date){const leave=annualLeaveForDate(learner,date);return{annualLeave:leave,collegeDay:collegeDayForDate(learner,date),labels:[...(leave.length?['Annual Leave']:[]),...(collegeDayForDate(learner,date)?['College Day']:[])]}}
export function learnerPlanningStatus(learner,visits,now=new Date()){const today=now.toISOString().slice(0,10);if(annualLeaveForDate(learner,today).length)return'annual-leave';const visit=upcomingVisits(visits,now).find(v=>v.learnerId===learner?.id);return visit?.type||'none'}
export function bookingAwareness(learner,date,visits,learners=[]){const selectedVisits=visitsForDate(visits,date).filter(v=>v.learnerId===learner?.id),otherVisits=visitsForDate(visits,date).filter(v=>v.learnerId!==learner?.id).map(visit=>({...visit,learner:learners.find(l=>l.id===visit.learnerId)}));return{availability:learnerAvailability(learner,date),selectedVisits,otherVisits,hasClash:!!(selectedVisits.length||otherVisits.length||annualLeaveForDate(learner,date).length)}}
export function rollingFiveDays(date=new Date()){const day=new Date(date.getFullYear(),date.getMonth(),date.getDate());return Array.from({length:5},(_,i)=>{const d=new Date(day);d.setDate(day.getDate()+i);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`})}
export function monthCalendarDates(month){const match=/^(\d{4})-(\d{2})$/.exec(String(month||''));if(!match)return[];const year=Number(match[1]),monthIndex=Number(match[2])-1,first=new Date(Date.UTC(year,monthIndex,1)),days=new Date(Date.UTC(year,monthIndex+1,0)).getUTCDate(),offset=(first.getUTCDay()+6)%7;return Array(offset).fill(null).concat(Array.from({length:days},(_,i)=>`${match[1]}-${match[2]}-${String(i+1).padStart(2,'0')}`))}
const normalName=value=>String(value||'').trim().replace(/\s+/g,' ');
export function compareLearnersByFirstName(a,b){const parts=learner=>normalName(learner?.name).split(' '),ap=parts(a),bp=parts(b),first=ap[0].localeCompare(bp[0],undefined,{sensitivity:'base'});return first||ap.slice(1).join(' ').localeCompare(bp.slice(1).join(' '),undefined,{sensitivity:'base'})||normalName(a?.name).localeCompare(normalName(b?.name))||String(a?.id||'').localeCompare(String(b?.id||''))}
export function groupLearnersByCourse(learners,courseFor){const groups=new Map();for(const learner of Array.isArray(learners)?learners:[]){const course=courseFor(learner),courseTitle=normalName(course?.course?.title)||'Unknown course',pathwayTitle=normalName(course?.course?.pathways?.find(x=>x.id===learner?.pathwayId)?.title),key=`${courseTitle}\0${pathwayTitle}`;if(!groups.has(key))groups.set(key,{courseTitle,pathwayTitle,title:pathwayTitle?`${courseTitle} — ${pathwayTitle}`:courseTitle,learners:[]});groups.get(key).learners.push(learner)}return [...groups.values()].sort((a,b)=>a.courseTitle.localeCompare(b.courseTitle,undefined,{sensitivity:'base'})||a.pathwayTitle.localeCompare(b.pathwayTitle,undefined,{sensitivity:'base'})).map(group=>({...group,learners:group.learners.sort(compareLearnersByFirstName)}))}
export const workStatus=record=>!record?'Not Started':record.status==='Completed'?'Complete':'Draft';
export function visitWork(visit,reviews=[],assessments=[]){return{review:['review','combined','catchup'].includes(visit?.type)?reviews.find(x=>x.id===visit?.reviewId):undefined,observation:['observation','combined'].includes(visit?.type)?assessments.find(x=>x.id===visit?.assessmentId):undefined}}
export const workingWeek=rollingFiveDays;
export const visitsForWeek=(visits,date=new Date())=>{const dates=new Set(workingWeek(date));return (Array.isArray(visits)?visits:[]).filter(v=>dates.has(v?.date))};
export const latestCompletedReview=(reviews,learnerId)=>(Array.isArray(reviews)?reviews:[]).filter(r=>r?.learnerId===learnerId&&r.status==='Completed'&&r.reviewType!=='Catch-up Review').sort((a,b)=>String(b.reviewDate||'').localeCompare(String(a.reviewDate||''))||String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')))[0]||null;
export const activeLearners=learners=>(Array.isArray(learners)?learners:[]).filter(l=>l&&l.status!=='withdrawn');
export function courseOverview(learners,courses){return [...activeLearners(learners).reduce((map,l)=>{const courseId=learnerCourseId(l);return map.set(courseId,(map.get(courseId)||0)+1)},new Map())].map(([courseId,count])=>({courseId,title:courses.get(courseId)?.course?.title||String(courseId||'Unknown course'),count})).sort((a,b)=>String(a.title).localeCompare(String(b.title)))}
export const nextVisit=(visits,now=new Date())=>upcomingVisits(visits,now)[0]||null;
export const googleMapsUrl=location=>`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(location||'')}`;
export function plannedReviewVisits(full,existing=[]){
 const keep=(Array.isArray(existing)?existing:[]).filter(v=>v?.sourceFullReviewId===full.id),fullVisit=keep.find(v=>v.planningRole==='next-full-review'||v.type==='review'),catchUp=keep.find(v=>v.planningRole==='catch-up'||v.type==='catchup'),base={learnerId:full.learnerId,time:'09:00',location:'',status:'planned',sourceFullReviewId:full.id};
 const result=[];
 if(full.nextReviewDate)result.push({...base,...fullVisit,id:fullVisit?.id||`full-${full.id}`,date:full.nextReviewDate,type:'review',planningRole:'next-full-review',reviewId:'',note:'Next Full Review'});
 if(full.catchUpRequired==='Yes'&&full.catchUpDate)result.push({...base,...catchUp,id:catchUp?.id||`catchup-${full.id}`,date:full.catchUpDate,type:'catchup',planningRole:'catch-up',reviewId:full.catchUpReviewId||catchUp?.reviewId||'',note:'Catch-up Review planned from full review'});
 return result;
}
